DESTDIR=~/Library/Developer/Xcode/Templates/Project\ Templates/Application
COORDINATORSTARTER-TEMPLATE="Coordinator Starter.xctemplate"
COORDINATORSTARTER-QUICKSPECS-TEMPLATE="Coordinator Starter Quick Specs.xctemplate"
COORDINATORSTARTER-SNAPSHOTTESTS-TEMPLATE="Coordinator Starter Snapshot Tests.xctemplate"

install:
	mkdir -p $(DESTDIR)
	cp -R $(COORDINATORSTARTER-TEMPLATE) $(DESTDIR)
	cp -R $(COORDINATORSTARTER-QUICKSPECS-TEMPLATE) $(DESTDIR)
	cp -R $(COORDINATORSTARTER-SNAPSHOTTESTS-TEMPLATE) $(DESTDIR)

uninstall:
	rm -rf $(DESTDIR)/$(COORDINATORSTARTER-TEMPLATE)
	rm -rf $(DESTDIR)/$(COORDINATORSTARTER-QUICKSPECS-TEMPLATE)
	rm -rf $(DESTDIR)/$(COORDINATORSTARTER-SNAPSHOTTESTS-TEMPLATE)
